"use client";

import 'bootstrap/dist/css/bootstrap.min.css';
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
// export const metadata = {
//   title: 'Auth',
//   description: 'Generated by Jayesh',
// }
const navLinks=[
  {name:"Register",href:"/register"},
  {name:"Login",href:"/login"},
  {name:"Forgot Password",href:"/forgot-password"},
]

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [input,setInput] = useState("");
  const pathname=usePathname();
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: '#f5f5f5',
          padding: '2rem',
        }}>
          <p>Header</p>
        </header>
        <div>
          <div><input value={input} onChange={e=>setInput(e.target.value)}></input></div>
          {navLinks.map((link)=>{
            const isActive=pathname===link.href || pathname.startsWith(link.href) && link.href!=="/";
            return(
              <Link className={isActive ?  "fw-bold me-4" : "text-primary me-4"} href={link.href} key={link.name}>{link.name}</Link>
            )
          })}
        </div>
        {children}
        <footer style={{
          backgroundColor: '#f5f5f5',
          padding: '2rem',
        }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
