import { Counter } from "./counter";

export const metadata={
    title: 'Counter',
    description: 'Generated by Jayesh',
}


 export default function CounterPage(){
    return (
        <div>
            <Counter/>
        </div>
    );
 }