import { ErrorWrapper } from "./error-wrapper"

export const metadata = {
  // default:"Next.js",
  title: {
    default: 'Next.js',
    template: '%s | Jayesh',
    // absolute: 'Next.js',
  },
  description: 'Generated by Jayesh',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: '#f5f5f5',
          padding: '2rem',
        }}>
          <p>Header</p>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer style={{
          backgroundColor: '#f5f5f5',
          padding: '2rem',
        }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
